### ISSUE TITLE
Gemini Support

### ISSUE THREAD

**Issue by baptistechretien** [peter2k/AnySelectPublic#2]
Hello,

Could you please explain to me how to add the Gemini Pro API?

Thank you in advance.

Best regards,

**Comment by peter2k** [comment]
Hi @baptistechretien ,

i just released a new version of AnySelect with Gemini support. You can enable it in AnySelect's settings. https://github.com/peter2k/AnySelectPublic/releases/tag/2.3.0
Have fun!

Best regards.
